### ISSUE TITLE
Create high level document

### ISSUE THREAD

**Issue by Xaptured** [Xaptured/microservice-thejackfolio_db#58]
Create high level document with pics and explanation of things.

## Subtasks

- [x] Should contain detail decription of all the repos.
- [x] Things I did in this project - key points
- [x] Instagram/YouTube APIs

**Comment by Xaptured** [comment]
All things are done hence closing this ticket
